require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VechiclesController do

  # This should return the minimal set of attributes required to create a valid
  # Vechicle. As you add validations to Vechicle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VechiclesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vechicles as @vechicles" do
      vechicle = Vechicle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vechicles).should eq([vechicle])
    end
  end

  describe "GET show" do
    it "assigns the requested vechicle as @vechicle" do
      vechicle = Vechicle.create! valid_attributes
      get :show, {:id => vechicle.to_param}, valid_session
      assigns(:vechicle).should eq(vechicle)
    end
  end

  describe "GET new" do
    it "assigns a new vechicle as @vechicle" do
      get :new, {}, valid_session
      assigns(:vechicle).should be_a_new(Vechicle)
    end
  end

  describe "GET edit" do
    it "assigns the requested vechicle as @vechicle" do
      vechicle = Vechicle.create! valid_attributes
      get :edit, {:id => vechicle.to_param}, valid_session
      assigns(:vechicle).should eq(vechicle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vechicle" do
        expect {
          post :create, {:vechicle => valid_attributes}, valid_session
        }.to change(Vechicle, :count).by(1)
      end

      it "assigns a newly created vechicle as @vechicle" do
        post :create, {:vechicle => valid_attributes}, valid_session
        assigns(:vechicle).should be_a(Vechicle)
        assigns(:vechicle).should be_persisted
      end

      it "redirects to the created vechicle" do
        post :create, {:vechicle => valid_attributes}, valid_session
        response.should redirect_to(Vechicle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vechicle as @vechicle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vechicle.any_instance.stub(:save).and_return(false)
        post :create, {:vechicle => {}}, valid_session
        assigns(:vechicle).should be_a_new(Vechicle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vechicle.any_instance.stub(:save).and_return(false)
        post :create, {:vechicle => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vechicle" do
        vechicle = Vechicle.create! valid_attributes
        # Assuming there are no other vechicles in the database, this
        # specifies that the Vechicle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vechicle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vechicle.to_param, :vechicle => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vechicle as @vechicle" do
        vechicle = Vechicle.create! valid_attributes
        put :update, {:id => vechicle.to_param, :vechicle => valid_attributes}, valid_session
        assigns(:vechicle).should eq(vechicle)
      end

      it "redirects to the vechicle" do
        vechicle = Vechicle.create! valid_attributes
        put :update, {:id => vechicle.to_param, :vechicle => valid_attributes}, valid_session
        response.should redirect_to(vechicle)
      end
    end

    describe "with invalid params" do
      it "assigns the vechicle as @vechicle" do
        vechicle = Vechicle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vechicle.any_instance.stub(:save).and_return(false)
        put :update, {:id => vechicle.to_param, :vechicle => {}}, valid_session
        assigns(:vechicle).should eq(vechicle)
      end

      it "re-renders the 'edit' template" do
        vechicle = Vechicle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vechicle.any_instance.stub(:save).and_return(false)
        put :update, {:id => vechicle.to_param, :vechicle => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vechicle" do
      vechicle = Vechicle.create! valid_attributes
      expect {
        delete :destroy, {:id => vechicle.to_param}, valid_session
      }.to change(Vechicle, :count).by(-1)
    end

    it "redirects to the vechicles list" do
      vechicle = Vechicle.create! valid_attributes
      delete :destroy, {:id => vechicle.to_param}, valid_session
      response.should redirect_to(vechicles_url)
    end
  end

end
